channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.2
- pip:
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.1
  - scipy==1.13.1
  - xgboost==2.1.1
  - flask==3.0.3
  - pytest==8.3.4
name: mlflow-env
